//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webapi_location.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LocationDb : DbContext
    {
        public LocationDb()
            : base("name=LocationDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<favorite_location> favorite_location { get; set; }
        public virtual DbSet<master_location> master_location { get; set; }
        public virtual DbSet<user_favorite> user_favorite { get; set; }
        public virtual DbSet<user_information> user_information { get; set; }
    
        public virtual ObjectResult<sp_FavoriteLocation_Result> sp_FavoriteLocation()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_FavoriteLocation_Result>("sp_FavoriteLocation");
        }
    
        public virtual int sp_insert(string location_name)
        {
            var location_nameParameter = location_name != null ?
                new ObjectParameter("location_name", location_name) :
                new ObjectParameter("location_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert", location_nameParameter);
        }
    
        public virtual ObjectResult<sp_UserFavoriteLocation_Result> sp_UserFavoriteLocation(string uid)
        {
            var uidParameter = uid != null ?
                new ObjectParameter("uid", uid) :
                new ObjectParameter("uid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_UserFavoriteLocation_Result>("sp_UserFavoriteLocation", uidParameter);
        }
    }
}
